services:
  app:
    image: testing-api-service
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_PASSWORD: root
      DB_USER: root
      DB_NAME: testingapi
    networks:
      - mynetwork
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
 
networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  mysql-data:
